### PR TITLE
Add Colmena CMS https://github.com/colmena/colmena-cms

### PR DESCRIPTION
**Pull request by beeman**
* Don't create a pull request to add a library, instead use [devarchy.com/angular-components](http://devarchy.com/angular-components).
* Only create a pull request to change the categorization.
* Open an issue if you are not sure how to change the categorization to fit a library you want to add.

I tried to add my project via the site, but currently Colmena CMS is not shipped as an NPM package, it's more of a starter app than a library/component. 

Not sure if it fits in this list, but thanks for considering.

### CODE REVIEW

**Comment by brillout** [comment]
Hi, thanks for the PR!

How about Starter Kit?

The Starter Kit category is getting large and we should add subsections to it. What kind of subsections do you think would make sense?

**Comment by beeman** [comment]
@brillout I've just moved the link to the Starter Kit section, did not see it before.

I'm not sure about the sections there. Maybe `Seeds`/`Generators` ?

**Comment by brillout** [comment]
Maybe depending on what the user wants to achieve? E.g. if I want to make a universal app -> `Starter Kit -> Universal`. If I want to make an admin interface -> `Starter Kit -> Admin Panel`. Seems to be more important than whether the library is a generator or a seed project

**Comment by beeman** [comment]
That makes total sense @brillout

**Comment by brillout** [comment]
Just merged it. Can't find time to add subcategories, @beeman up for the job?

**Pull request closed without merging**
