### PR TITLE
Add virtual scroll category. Append virtual scroll component

### PR DESCRIPTION
**Pull request by dinony**
Append Virtual Scroll to Contents. Append component

### CODE REVIEW

**Comment by brillout** [comment]
Thanks for the PR.

Maybe it would be good to add a text in `od-virtualscroll`'s readme explaining what virtualization is and what problem it is solving?

What do you think of naming the category `List Virtualization` or `Virtualized List` or `Virtualization`?

Totally looking forward to add a virtualization library to the catalog.

**Comment by dinony** [comment]
Agreed, much better category naming - I'm ok with both proposals.

**Comment by dinony** [comment]
Hi @brillout, do you think that you can manage to merge this PR anytime soon?

**Comment by brillout** [comment]
Yes! Rename the category and I'll merge.

**Comment by brillout** [comment]
We could go for `List Virtualization` since it's called like that on the React catalog

**Comment by dinony** [comment]
Renamed!

**Comment by BioPhoton** [comment]
Is this repo still active? List Virtualisation would be awesome to have in here. :-)

**Comment by dinony** [comment]
@brillout I believe in your abilities, you can do it!

**Comment by brillout** [comment]
Thanks for the PR!

**Pull request merged**
