### PR TITLE
Rename of ng2-translate to ngx-translate

### PR DESCRIPTION
**Pull request by ocombe**
Hello,

ng2-translate has been renamed ngx-translate.

### CODE REVIEW

**Comment by brillout** [comment]
Hello,

done in https://github.com/brillout/awesome-angular-components/commit/5bb5739e19952f04efda27b8f1912611b65c222a.

Let me know if there is a good reason to link to the website instead of the GitHub repo.

**Comment by ocombe** [comment]
I link to the website because with version 6 the library is going modular, which means that I now use a namespace @ngx-translate and then I split the lib into multiple modules (for now the core and the loader), so it's no longer just one repository on github

**Comment by brillout** [comment]
Ok I see but a GitHub repo is still required to have a stars count.
For the list to stay consistent I'll keep the entry pointing to the core repo, hope it's ok.

**Comment by ocombe** [comment]
Sure, no problem! :-)

>

**Pull request closed without merging**
